spring:
  application:
    name: RestAPI
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379
    web:
      pageable:
        serialization-mode: via_dto

server:
  port: 8000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  valid-duration: 3600
  refreshable-duration: 2592000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
