ALTER TABLE tbl_users ADD created_at DATETIME2 DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tbl_users ADD updated_at DATETIME2 DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tbl_users ADD created_by VARCHAR(255);
ALTER TABLE tbl_users ADD updated_by VARCHAR(255);

ALTER TABLE tbl_roles ADD created_at DATETIME2 DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tbl_roles ADD updated_at DATETIME2 DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tbl_roles ADD created_by VARCHAR(255);
ALTER TABLE tbl_roles ADD updated_by VARCHAR(255);

ALTER TABLE tbl_permissions ADD created_at DATETIME2 DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tbl_permissions ADD updated_at DATETIME2 DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tbl_permissions ADD created_by VARCHAR(255);
ALTER TABLE tbl_permissions ADD updated_by VARCHAR(255);
